### ISSUE TITLE
Example of side bar icons?

### ISSUE THREAD

**Issue by rscott78** [AlastairTaft/draft-js-editor#10]
Hello -

Can you provide an example of how to customize the side bar icons? I'd like to be able to add more than just the "Big T" header one and the "Small T" header 2.

**Comment by AlastairTaft** [comment]
Sorry for the late reply. 

I plan on reworking the code for side bar buttons to work in the same pluggable way the inline buttons work. Won't be able to tackle this anytime soon though. 

If you're desperate feel free to submit a pull request, looking at how the inline buttons work is a good place to start.

**Comment by AlastairTaft** [comment]
Fixed with #12
