### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by nikgraf** [AlastairTaft/draft-js-editor#3]
Do you have any demo online?

**Comment by AlastairTaft** [comment]
Not at the moment. But it's easy to get going. Just  clone the repo, run `npm install`, `npm start` then visit http://localhost:3000

**Comment by nikgraf** [comment]
Will give it a try. Still I recommend a demo page so people can quickly checkout the latest version. Way easier then checking out a repo :smile:

**Comment by AlastairTaft** [comment]
Yeah I agree it would be nice. Hopefully will find time to set one up soon.

**Comment by nikgraf** [comment]
btw I added your editor to the awesome-draft-js repo: https://github.com/nikgraf/awesome-draft-js

**Comment by AlastairTaft** [comment]
Thanks :)
