### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by satyadeeproat** [AlastairTaft/draft-js-editor#6]
Hi, 
while uploading image same as you are doing, I am getting the file as undefined
handleFileInput(e){
          // This just converts e.target.files form a FileList to an Array
          var files = Array.prototype.slice.call(e.target.files, 0)
          files.forEach(this.insertFile)
        };

**Comment by AlastairTaft** [comment]
Only things I can think of:
- Testing on a different browser? I used Chrome when I developed that example
- Browser security preventing you from accessing the file you selected
- Wrong `this` context while iterating the forEach loop

I take it your talking about the image upload example code? Check that there is definitely some values in the `e.target.files` array first.

**Comment by AlastairTaft** [comment]
Feel free to re-open if you are still having issues.

**Comment by satyadeeproat** [comment]
Yes I was having some problem in e.target.files. Resolved it now. Thanks :)
