### ISSUE TITLE
Improvement suggestion: Allow styling for PopoverControl and SideControl independently 

### ISSUE THREAD

**Issue by joekrump** [AlastairTaft/draft-js-editor#7]
Hi, I think this editor provides a great starting point for an inline content editor. I'm working on integrating this in an app which has a dark background and therefore I set `iconColor` to a light color. The issue is that the background color for the PopoverControl is a light color also and therefore the icons do not show up well in it. 

It would be great if I could pass something such as a `popoverStyle` prop to the editor which would allow me to pass custom styles for it. ex. `popoverStyle={{backgroundColor: '#000', color: '#fff'}}`

Thanks

**Comment by AlastairTaft** [comment]
Thanks for the suggestion, I agree it would be useful I'll see if I can incorporate it in soon.

**Comment by AlastairTaft** [comment]
Should now be implemented and published, version 1.3.0
